name: Unzip a-stock-data

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip file
        run: |
          if [ -f a-stock-data-main.zip ]; then
            unzip a-stock-data-main.zip
            cp -r a-stock-data-main/* .
            rm -rf a-stock-data-main a-stock-data-main.zip
          else
            echo "ZIP不存在，可能是上次已解压但推送失败"
          fi

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --cached --quiet || git commit -m "解压a-stock-data源码"
          git push
